### PR TITLE
Update snippets

### PR DESCRIPTION
**Pull request by onmyway133**
- Update to be in Swift 3
- Add `swiftguardself`
- Update README

### CODE REVIEW

**Comment by zenangst** [comment]
Why do we have a prefix for the completions?

**Comment by onmyway133** [comment]
@zenangst to make it easy to remember, just type `swift` and get all the suggestions

**Comment by zenangst** [comment]
@onmyway133 I would rather have them be contextual to the things that I'm setting out to do.

**Comment by onmyway133** [comment]
@zenangst Maybe it's just me, but that way snippets just appear interleaved with the statements, like typing `guard` also shows the snippet

**Comment by zenangst** [comment]
@onmyway133 in my opinion that is the entire point of having the snippets in the first place 😎

**Review by zenangst — APPROVED** [review]

**Pull request merged**
